dashboard/urls.py
from django.urls import path
from .views import (
    dashboardView,
)

app_name = 'dashboard'

urlpatterns = [
    path('', dashboardView, name='home'),
]

fabrica/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('users/', include('users.urls')),
    path('', include('dashboard.urls')),
    path('products/', include('products.urls')),
]

users/urls.py
from django.urls import path

from .views import (
    loginView,
    logoutUser,
)
app_name = 'users'

urlpatterns = [
    path('login/', loginView, name='login'),
    path('logout/', logoutUser, name='logout'),
]

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <!-- Meta Info -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %} {% endblock title %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.rtl.min.css"
    integrity="sha384-nU14brUcp6StFntEOOEBvcJm4huWjB0OcIeQ3fltAfSmuZFrkAif0T+UtNGlKKQv" crossorigin="anonymous">


    <!-- Chartjs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js"></script>

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}" </head>

<body>
    <!-- Navbar-->
    {% include 'navbar.html' %}
    <!-- Content -->
    <!-- Alerts of bootstrap -->
    <div class="row p-2 mx-2">
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                    <!--span aria-hidden="true">&times;</span-->
                </button>
                {{ message | safe }}
            </div>
            {% endfor %}
    </div>

        {% block content %}

        {% endblock content %}
        <!-- Scripts -->

        <!-- Separate Popper and Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
        <!-- Logo Home Link-->
      <a class="navbar-brand" href="{% url 'dashboard:home' %}">
        <img src="{% static 'images/ai.png' %}" width="30" height="30" alt="">
        DataSoft
      </a>
      <!-- Collapse toggle small page-->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <!-- Home Page -->
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" height="16" width="18" viewBox="0 0 576 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M575.8 255.5c0 18-15 32.1-32 32.1h-32l.7 160.2c0 2.7-.2 5.4-.5 8.1V472c0 22.1-17.9 40-40 40H456c-1.1 0-2.2 0-3.3-.1c-1.4 .1-2.8 .1-4.2 .1H416 392c-22.1 0-40-17.9-40-40V448 384c0-17.7-14.3-32-32-32H256c-17.7 0-32 14.3-32 32v64 24c0 22.1-17.9 40-40 40H160 128.1c-1.5 0-3-.1-4.5-.2c-1.2 .1-2.4 .2-3.6 .2H104c-22.1 0-40-17.9-40-40V360c0-.9 0-1.9 .1-2.8V287.6H32c-18 0-32-14-32-32.1c0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7L564.8 231.5c8 7 12 15 11 24z"/></svg>
            </a>
          </li>
            <!-- Admin -->
          <li class="nav-item">
            <a class="nav-link" href="./admin">Admin</a>
          </li>
          <!-- User Profile -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">My Profile</a></li>
              <li><a class="dropdown-item" href="#">Edit Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Configs</a></li>
            </ul>
          </li>
          <!-- Logout *NEDD TO WORK ON IT* -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
          </li>
        </ul>
        <!-- Search Bar -->
        <form class="d-flex" role="search">
          <input name='q' class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
</nav>