fabrica/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('users/', include('users.urls')),
    path('', include('dashboard.urls')),
    path('products/', include('products.urls')),
]

products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required


from .views import (
    ProductListView,
    deleteProduct,
    updateProduct,

    viewInventary,

    viewProduction,
    editProduction,
)

app_name = 'products'

urlpatterns = [
    path('', login_required(ProductListView.as_view()), name='products'),
    path('delete/<str:pk>/', deleteProduct, name='delete'),
    path('update/<str:pk>/', updateProduct, name='update'),
    path('inv/', viewInventary, name='inv'),
    path('productions/', viewProduction, name='productions'),
    path('edit-production/<str:pk>/', editProduction, name='edit-production'),

]

users/urls.py
from django.urls import path

from .views import (
    loginView,
    logoutUser,
)
app_name = 'users'

urlpatterns = [
    path('login/', loginView, name='login'),
    path('logout/', logoutUser, name='logout'),
]

products/models.py
from django.db import models
from django.utils import timezone
from .utils import generate_code


from employees.models import Operator


class Product(models.Model):
    """
    Produtos de venda final
    """
    ITEM_TYPE = {
        'HEAT SHIELD' : "HEAT SHIELD",
        "BRACKET" : "BRACKET",
        "EXHAUST VALVE" : "EXHAUST VALVE",
    }
    name = models.CharField(max_length=20)
    category = models.CharField(max_length=20, choices=ITEM_TYPE, blank=True)
    price = models.FloatField(help_text = 'euros each')
    image = models.ImageField(upload_to="products", default='default.png')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)



    def __str__(self):
        return f'{self.name} - {self.category}'

class Production(models.Model):
    production_id = models.CharField(max_length=12, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True)
    operator = models.ForeignKey(Operator, on_delete=models.CASCADE, blank=True)

    date = models.DateField(blank=True)
    quantity = models.IntegerField(blank=True)
    hours_taken = models.IntegerField(blank=True)
    notes = models.TextField(default='No Notes')

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f'{self.operator.first_name} - {self.quantity}'

    def save(self, *args, **kwargs):
        if self.production_id == "":
            self.production_id = generate_code()
        if self.date is None:
            self.date = timezone.now()
        return super().save(*args, **kwargs)        

class Inventary(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    productions = models.ManyToManyField(Production)
    total_quantity = models.IntegerField(blank=True, null=True)

    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.product.name} - {self.total_quantity} available stock'

products/forms.py
from django import forms
from django.forms.models import BaseModelFormSet

from .models import Product, Production


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['image']

class DateInput(forms.DateInput):
    input_type = 'date'

class ProductionForm(forms.ModelForm):
    class Meta:
        model = Production
        fields = '__all__'
        widgets = {
            'date': DateInput(),
        }

class BaseProductionFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseProductionFormSet, self).__init__(*args, **kwargs)
        self.queryset = Production.objects.none()

products/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory
from django.forms.models import modelformset_factory

from django.db.models import Q

from .models import Product, Inventary, Production
from .forms import ProductForm, ProductionForm, BaseProductionFormSet


# Produtos

class ProductListView(ListView):
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'

    def get_queryset(self):
        query = self.request.GET.get('q')  # Obtém o parâmetro de consulta da URL
        object_list = Product.objects.all()

        if query:
            # Filtra os produtos pelo nome ou categoria usando Q objects
            object_list = object_list.filter(Q(name__icontains=query) | Q(category__icontains=query))

        return object_list


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProductForm()
        return context

    def post(self, request, *args, **kwargs):
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product has been created!', "alert-success alert-dismissible")
        else:
            messages.error(request, 'Create Product failed!', "alert-danger alert-dismissible")
        return self.get(request, *args, **kwargs)

@login_required(login_url='users:login')
def deleteProduct(request, pk):
    product = Product.objects.get(id=pk)
    if request.method == 'POST':
        product.delete()
        messages.success(request, 'Product Deleted!', "alert-success alert-dismissible")
        return redirect('products:products')
    return render(request, 'products/delete.html', {'obj': product})

@login_required(login_url='users:login')
def updateProduct(request, pk):
    product = Product.objects.get(id=pk)
    form = ProductForm(instance=product)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product Updated!', "alert-success alert-dismissible")
            return redirect('products:products')

    context = {
        'form':form,
        'product':product,

    }
    return render(request, 'products/update.html', context)

# Inventario
@login_required(login_url='users:login')
def viewInventary(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    inv = Inventary.objects.filter(
        Q(product__name__icontains=q)
    )


    context = {
        'inv' : inv,

    }
    return render(request, 'products/inventary.html', context)


# Produção
@login_required(login_url='users:login')
def viewProduction(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''

    productions = Production.objects.filter(
        Q(operator__first_name__icontains=q) |
        Q(product__name__icontains=q)
    )
        # Criação do formset com base no formulário do modelo Production
    ProductionFormSet = modelformset_factory(Production, ProductionForm, extra=1, formset=BaseProductionFormSet)

    formset = ProductionFormSet(queryset=Production.objects.none())

    if request.method == 'POST':
        form = ProductionFormSet(request.POST)
        if form.is_valid():
            form.save()
            return redirect('products:productions')

            messages.success(request, 'Productions added with success!', "alert-success alert-dismissible")


    context = {
        'productions': productions,
        'formset':formset,
    }

    return render(request, 'products/production.html', context)

@login_required(login_url='users:login')
def editProduction(request, pk):
    production = Production.objects.get(id=pk)
    form = ProductionForm(instance=production)

    if request.method == 'POST':
        form = ProductionForm(request.POST, instance=production)
        if form.is_valid():
            form.save()
            messages.success(request, 'Production Updated!', 'alert-success alert-dismissible')
            return redirect('products:productions')
        else:
            messages.error(request, 'Something went wrong!', 'alert-warning alert-dismissible')

    context = {
        'form':form
    }

    return render(request, 'products/edit.html', context )

products/templates/products/add_productions.html
<div class="container">
    <div class="row text-center">
        <h2>Add new Production</h2>
    </div>
    <div class="row my-4">
        <!-- Table start-->
        <div class="col-ms-2 text-center">
            <form method="post" action="{% url 'products:productions' %}">
                {% csrf_token %}
                {{ formset.management_form }}
                <table class="table bg-white">
                    <thead class="thead-dark">
                        <tr class="table-dark">
                            <th scope="col">Date</th>
                            <th scope="col">Product</th>
                            <th scope="col">Operator</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Hours</th>
                            <th scope="col">Notes</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for form in formset %}
                        <tr class="form-row">
                            <td>{{ form.date }}</td>
                            <td>{{ form.product }}</td>
                            <td>{{ form.operator }}</td>
                            <td>{{ form.quantity }}</td>
                            <td>{{ form.hours_taken }}</td>
                            <td>{{ form.notes }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <input type="submit" value="Add Prod..." class="btn btn-outline-dark btn-lock text-center">
            </form>
        </div>
    </div>
</div>

products/templates/products/delete.html
{% extends 'main.html' %}


{% block content %}
<div class="content p-2">
    <div class="row mt-4">
        <div class="col-sm4">
            <div class="card text-center">
                <div class="card-header bg-dark text-white">
                Sure ?
                </div>
                <form class="form" action="" method="POST">
                    {% csrf_token %}
                    <div class="card-body">
                        <h5 class="card-title">...</h5>
                        <p class="card-text">Do you want to delete {{obj.name}}??</p>
                        <input class="btn btn-outline-dark btn-block" type="submit" value="Confirm">
                        <a href="{{request.META.HTTP_REFERER}}" class="btn btn-outline-dark btn-block">No, go back!</a>
                        </div>
                        <div class="card-footer text-body-secondary">
                        You can not come back from this!
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

products/templates/products/edit.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content p-2">
    <div class="row mt-4">
        <div class="col-sm4">
            <div class="card text-center">
                <div class="card-header bg-dark text-white">
                    {{production.name}}
                </div>
                <form class="form" action="" method="POST">
                    {% csrf_token %}
                    <div class="card-body my-2">
                        {{form | crispy}}
                        <input class="btn btn-outline-dark btn-block my-4" type="submit" value="Confirm">
                        <a href="{{request.META.HTTP_REFERER}}" class="btn btn-outline-dark btn-block">No, go back!</a>
                        </div>
                        <div class="card-footer text-body-secondary">
                        >...
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

products/templates/products/inventary.html
{% extends 'main.html' %}
{% block content %}

<div class="container">
    <div class="row text-center">
        <h2>Inventary</h2>
    </div>
    <div class="row my-4">
            <!-- Table start-->
            <div class="col-ms-2">
                <table class="table bg-white">
                    <thead class="thead-dark">
                    <tr class="table-dark">
                        <th scope="col">#</th>
                        <th scope="col">Product</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Activity</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for obj in inv %}
                    <tr>
                        <th scope="row">{{obj.id}}</th>
                        <td>{{obj.product.name}}</td>
                        <td>{{obj.total_quantity}}</td>
                        <td class="text-center">
                            <a class='btn btn-outline-success btn-sm' href="">View</a>
                        </td>
                    </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
            <!-- Table end-->
</div>

    <!-- Graphs-->
        <!-- First-->
        <div class="container">
            <div class="row my-5">
                <div class="col-md-6">
                    <div class="bg-white">
                        <canvas id="myChart1" width="400" height="300"></canvas>
                        <script>
                            var ctx = document.getElementById('myChart1').getContext('2d');
                            var myChart1 = new Chart(ctx, {
                                type: 'pie',
                                data: {
                                    labels: [{% for obj in inv %} '{{obj.product.name}}', {% endfor %}],
                                    datasets: [{
                                        label: 'Products',
                                        data: [{% for obj in inv %} '{{obj.total_quantity}}', {% endfor %}],
                                        backgroundColor: [
                                            'rgba(255, 99, 132, 0.6)',
                                            'rgba(255, 159, 64, 0.6)',
                                            'rgba(255, 205, 86, 0.6)',
                                            'rgba(75, 192, 192, 0.6)',
                                            'rgba(54, 162, 235, 0.6)',
                                            'rgba(153, 102, 255, 0.6)',
                                            'rgba(201, 203, 207, 0.6)'
                                        ],
                                        borderColor: [
                                            'rgb(255, 99, 132, 0.6)',
                                            'rgb(255, 159, 64, 0.6)',
                                            'rgb(255, 205, 86, 0.6)',
                                            'rgb(75, 192, 192, 0.6)',
                                            'rgb(54, 162, 235, 0.6)',
                                            'rgb(153, 102, 255, 0.6)',
                                            'rgb(201, 203, 207, 0.6)'
                                        ],
                                        borderWidth: 1
                                    }]
                                },
                                options: {
                                    scales: {
                                        yAxes: [{
                                            ticks: {
                                                beginAtZero: true
                                            }
                                        }]
                                    }
                                }
                            });
                        </script>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="bg-white">
                        <canvas id="myChart2" width="400" height="300"></canvas>
                        <script>
                            var ctx = document.getElementById('myChart2').getContext('2d');
                            var myChart2 = new Chart(ctx, {
                                type: 'bar',
                                data: {
                                    labels: [{% for obj in inv %} '{{obj.product.name}}', {% endfor %}],
                                    datasets: [{
                                        label: 'Products',
                                        data: [{% for obj in inv %} '{{obj.total_quantity}}', {% endfor %}],
                                        backgroundColor: [
                                            'rgba(255, 99, 132, 0.6)',
                                            'rgba(255, 159, 64, 0.6)',
                                            'rgba(255, 205, 86, 0.6)',
                                            'rgba(75, 192, 192, 0.6)',
                                            'rgba(54, 162, 235, 0.6)',
                                            'rgba(153, 102, 255, 0.6)',
                                            'rgba(201, 203, 207, 0.6)'
                                        ],
                                        borderColor: [
                                            'rgb(255, 99, 132, 0.6)',
                                            'rgb(255, 159, 64, 0.6)',
                                            'rgb(255, 205, 86, 0.6)',
                                            'rgb(75, 192, 192, 0.6)',
                                            'rgb(54, 162, 235, 0.6)',
                                            'rgb(153, 102, 255, 0.6)',
                                            'rgb(201, 203, 207, 0.6)'
                                        ],
                                        borderWidth: 1
                                    }]
                                },
                                options: {
                                    scales: {
                                        yAxes: [{
                                            ticks: {
                                                beginAtZero: true
                                            }
                                        }]
                                    }
                                }
                            });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    <!-- End Graphs -->


{% endblock content %}

products/templates/products/old_add_productions.html
<h3>Add Productions</h3>
<div id="form_set">
    <form method="post" action="{% url 'products:productions' %}">
        {% csrf_token %}
        {{ formset.management_form }}
        <table class='table' id="production_table">
            <thead class="thread-dark">
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Product</th>
                    <th scope="col">Operator</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Hours</th>
                </tr>
            </thead>
            <tbody id="inlineform">
                {% for form in formset %}
                    <tr class="form-row">
                        <td>{{ form.date }}</td>
                        <td>{{ form.product }}</td>
                        <td>{{ form.operator }}</td>
                        <td>{{ form.quantity }}</td>
                        <td>{{ form.hours_taken }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <input type="button" value="Add More" id="add_more">
        <input type="submit" value="Save Productions">
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function() {
        // Função para clonar a primeira linha e adicionar à tabela
        function cloneRow() {
            var row = $(".form-row:first").clone(true);  // true para clonar também os eventos
            row.find('input').val('');  // Limpar os valores dos campos
            $("#inlineform").append(row);
        }

        // Manipulador de evento para o botão "Add More"
        $("#add_more").on('click', function() {
            cloneRow();
        });
    });
</script>

products/templates/products/production.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

{% include 'products/add_productions.html' %}


<div class="container">
    <div class="row text-center">
        <h2>Production</h2>
    </div>
    <div class="row my-4">
        <!-- Table start-->
        <div class="col-ms-2 text-center">
            <table class="table bg-white">
                <thead class="thead-dark">
                    <tr class="table-dark">
                        <th scope="col">#</th>
                        <th scope="col">Date</th>
                        <th scope="col">Product</th>
                        <th scope="col">Operator</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Hours</th>
                        <th scope="col">Notes</th>
                        <th scope="col">Activity</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in productions %}
                    <tr>
                        <th scope="row">{{obj.id}}</th>
                        <td>{{obj.date}}</td>
                        <td>{{obj.product.name}}</td>
                        <td>{{obj.operator.first_name}}</td>
                        <td>{{obj.quantity}}</td>
                        <td class="text-center">{{obj.hours_taken}}</td>
                        <td>{{obj.notes}}</td>
                        <td class="text-center">
                            <a class='btn btn-outline-success btn-sm' href="">View Prod</a>
                            <a class='btn btn-dark btn-sm' href="{% url 'products:edit-production' obj.id %}">Edit</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!-- Table end-->
</div>


{% endblock content %}

products/templates/products/products.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}



<div class="container">
    <div class="row text-center">
        <h2> Products </h2>
    </div>
    <div class="row my-4">
        <div class="col-md-4 ">
            <!-- Adicionar dados form-->
            <div class="border bg-white p-4">
                <h4>Add Products</h4>
                <hr>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group my-2">
                        {{ form | crispy }}
                    </div>
                
                
                    <input class="btn btn-outline-dark btn-block my-2" type="submit" value="Add products....">
                </form>

            </div>
        </div>
        <!-- Table start-->
        <div class="col-md-8">
            <table class="table bg-white">
                <thead class="thead-dark">
                <tr class="table-dark">
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Price</th>
                    <th scope="col">Activity</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                <tr>
                    <th scope="row">{{obj.id}}</th>
                    <td>{{obj.name}}</td>
                    <td>{{obj.category}}</td>
                    <td>{{obj.price}} euros</td>
                    <td>
                        <a class='btn btn-dark btn-sm' href="{% url 'products:update' obj.id %}">Edit</a>
                        <a class='btn btn-danger btn-sm' href="{% url 'products:delete' obj.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- Table end-->
    </div>
</div>




{% endblock content %}

products/templates/products/update.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content p-2">
    <div class="row mt-4">
        <div class="col-sm4">
            <div class="card text-center">
                <div class="card-header bg-dark text-white">
                    {{product.name}}
                </div>
                <form class="form" action="" method="POST">
                    {% csrf_token %}
                    <div class="card-body my-2">
                        {{form | crispy}}
                        <input class="btn btn-outline-dark btn-block my-4" type="submit" value="Confirm">
                        <a href="{{request.META.HTTP_REFERER}}" class="btn btn-outline-dark btn-block">No, go back!</a>
                        </div>
                        <div class="card-footer text-body-secondary">
                        >...
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}